App\Entity\Operation:
    properties:
        amount:
            - Type:
                type: integer
                message: The value {{ value }} is not a valid {{ type }}.
                groups: [add]
        comment:
            - Length:
                min: 10
                max: 50
                groups: [add]
        paymentType:
             - NotNull: { groups: [add] }
        purpose:
             - NotNull: { groups: [add] }


